name: Test Regression Scenarios

on: push

jobs:

  local-cli-regression:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        interaction-count: [0, 1, 100, 1000, 10000]
        #rust-diff-engine: ["true"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: "copy input data"
        shell: bash
        run: |
          MAX=${{ matrix.interaction-count }}
          touch input-interactions-$MAX.jsonl
          for i in $(seq 1 $MAX);
          do
            cat input-interactions.jsonl >> input-interactions-$MAX.jsonl
            echo >> input-interactions-$MAX.jsonl
          done
          cat input-interactions-$MAX.jsonl
      - name: "ls"
        shell: bash
        run: ls -lah
      - name: "run diff"
        shell: bash
        run: |
          MAX=${{ matrix.interaction-count }}
          cat input-interactions-$MAX.jsonl | ./optic_diff.exe input-events.json
      - name: "run diff"
        shell: bash
        run: |
          MAX=${{ matrix.interaction-count }}
          ./optic_diff.exe input-events.json < input-interactions-$MAX.jsonl
